-- LankaConnect Customer Care System (CCMS)
-- Database DDL Schema (MS SQL Server / ANSI SQL Compatible)

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(200) NOT NULL,
    email VARCHAR(150) NOT NULL UNIQUE,
    phone VARCHAR(30),
    role VARCHAR(50) NOT NULL, -- CUSTOMER, AGENT, STAFF, MANAGER, ADMIN
    department VARCHAR(100),
    subscription_start_date DATE,
    loyalty_tier VARCHAR(20), -- BRONZE, SILVER, GOLD (For Customers only)
    active BOOLEAN DEFAULT TRUE,
    verified BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE complaints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    complaint_code VARCHAR(50) NOT NULL UNIQUE,
    title VARCHAR(255) NOT NULL,
    category VARCHAR(100) NOT NULL,
    description TEXT NOT NULL,
    region VARCHAR(100) NOT NULL,
    priority VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    customer_id BIGINT,
    customer_name VARCHAR(200),
    customer_email VARCHAR(150),
    customer_phone VARCHAR(30),
    assigned_department VARCHAR(100),
    assigned_officer_id BIGINT,
    assigned_officer_name VARCHAR(200),
    assigned_staff_id BIGINT,
    assigned_staff_name VARCHAR(200),
    resolution_notes TEXT,
    attachment_file_name VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP NULL
);

CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_code VARCHAR(50) NOT NULL UNIQUE,
    complaint_id BIGINT,
    complaint_code VARCHAR(50),
    customer_id BIGINT,
    customer_name VARCHAR(200),
    title VARCHAR(255) NOT NULL,
    priority VARCHAR(50) NOT NULL,
    status VARCHAR(50) NOT NULL,
    assigned_department VARCHAR(100),
    assigned_staff_id BIGINT,
    assigned_staff_name VARCHAR(200),
    due_date TIMESTAMP NULL,
    overdue BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    resolved_at TIMESTAMP NULL
);

CREATE TABLE ticket_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT,
    ticket_code VARCHAR(50),
    changed_by VARCHAR(200),
    user_role VARCHAR(50),
    previous_status VARCHAR(50),
    new_status VARCHAR(50),
    remarks TEXT,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE chat_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id BIGINT NOT NULL,
    customer_name VARCHAR(200) NOT NULL,
    agent_id BIGINT,
    agent_name VARCHAR(200),
    status VARCHAR(50) NOT NULL, -- QUEUED, ACTIVE, TRANSFERRED, CLOSED
    topic VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    closed_at TIMESTAMP NULL
);

CREATE TABLE chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,
    sender_name VARCHAR(200) NOT NULL,
    sender_role VARCHAR(50) NOT NULL,
    message TEXT NOT NULL,
    file_name VARCHAR(255),
    file_url VARCHAR(500),
    is_read BOOLEAN DEFAULT FALSE,
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE feedback (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ticket_id BIGINT,
    ticket_code VARCHAR(50),
    complaint_id BIGINT,
    complaint_code VARCHAR(50),
    customer_id BIGINT NOT NULL,
    customer_name VARCHAR(200),
    rating INT NOT NULL,
    category VARCHAR(100),
    comments TEXT,
    negative_follow_up_required BOOLEAN DEFAULT FALSE,
    follow_up_status VARCHAR(50),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE alert_thresholds (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    region VARCHAR(100) NOT NULL UNIQUE,
    threshold_count INT NOT NULL DEFAULT 3,
    time_window_hours INT NOT NULL DEFAULT 1,
    active BOOLEAN DEFAULT TRUE,
    last_triggered_at TIMESTAMP NULL,
    last_alert_message TEXT
);

CREATE TABLE user_activity_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT,
    username VARCHAR(100),
    user_role VARCHAR(50),
    action VARCHAR(100) NOT NULL,
    details TEXT,
    ip_address VARCHAR(100),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE generated_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    report_name VARCHAR(255) NOT NULL,
    start_date VARCHAR(50),
    end_date VARCHAR(50),
    generated_by VARCHAR(200),
    manager_id BIGINT,
    record_count INT,
    file_format VARCHAR(20),
    report_data_json TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

